apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "frontend.fullname" . }}-policy
  namespace: default
  labels:
    app: {{ include "frontend.name" . }}
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "frontend.name" . }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.serviceDependencies.ingressControllerAppLabel }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Values.serviceDependencies.aiServiceAppLabel }}
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
