apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "frontend.fullname" . }}-policy
  namespace: default
  labels:
    app: {{ include "frontend.name" . }}
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "frontend.name" . }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app: ingress-nginx-controller
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ include "ai-service.name" . }} # This line is now templated
