apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    app: {{ include "frontend.name" . }}
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "frontend.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
